name: Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse_build:
    uses: Packet-Batch/pktbatch-rs/.github/workflows/build.yml@main
  run:
    needs: reuse_build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from Build workflow
      uses: actions/download-artifact@v4
      with:
        name: build-output
    - name: Run apt update
      run: sudo apt update
    - name: Install LibELF
      run: sudo apt install -y libelf-dev
    - name: List files
      run: ls -la
    - name: Add execute permissions to executable file
      run: sudo chmod +x ./pktbatch
    - name: Run Packet Batch with help menu
      run: sudo ./pktbatch -h
